gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
gemini.api.key=AIzaSyDHpC9S2PQYEr-dWfRk_gg3RtYl4J28i0A
TWILIO_ACCOUNT_SID=ACc7402efcdeb55d3072a33c8e68fe252f
TWILIO_AUTH_TOKEN=7e1c2e5b0ce29463108d5e922fdd6451
TWILIO_FROM=+12272741547
TWILIO_TO=+21658281778
